language: php
php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

addons:
  sonarcloud:
    organization: "arturschaefer-github" # the key of the org you chose at step #3
    token:
      secure: 02fa236cab4aeff818c6bdad220c29bfb3146b89 # encrypted value of your token

script:
  - sonar-scanner

notifications:
    slack: tcc-estudo-de-caso:loPMzuvXJIY1GezgAroKcGoi
