language: php
php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

addons:
  sonarcloud:
    organization: "arturschaefer-github" # the key of the org you chose at step #3
    token:
      secure: 29fab3a6b8222e4262af64d28267ad87915b6f73 # encrypted value of your token
